# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/spider_entity/breeder.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spider_common.proto.spider import parse_setting_pb2 as spider__common_dot_proto_dot_spider_dot_parse__setting__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!proto/spider_entity/breeder.proto\x1a.spider_common/proto/spider/parse_setting.proto\"\x9d\x02\n\x0e\x42reederMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ntarget_url\x18\x03 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65lete_time\x18\x05 \x01(\x05\x12\x12\n\nretry_time\x18\x06 \x01(\x03\x12\x13\n\x0b\x66inish_time\x18\x07 \x01(\x03\x12-\n\x06status\x18\x08 \x01(\x0e\x32\x1d.BreederMessage.BreederStatus\x12\x19\n\x11parse_setting_ids\x18\t \x03(\t\"@\n\rBreederStatus\x12\x0b\n\x07\x43REATED\x10\x00\x12\t\n\x05RETRY\x10\x01\x12\n\n\x06\x46INISH\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.spider_entity.breeder_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BREEDERMESSAGE._serialized_start=86
  _BREEDERMESSAGE._serialized_end=371
  _BREEDERMESSAGE_BREEDERSTATUS._serialized_start=307
  _BREEDERMESSAGE_BREEDERSTATUS._serialized_end=371
# @@protoc_insertion_point(module_scope)
